// Weapon definitions and stats
// All original weapons - no copyrighted content

export const WEAPONS = {
  rifle: {
    id: 'rifle',
    name: 'Assault Rifle',
    type: 'primary',
    price: 2700,
    damage: 30,
    headshotMultiplier: 3.0,
    legMultiplier: 0.75,
    fireRate: 100, // ms between shots
    automatic: true,
    magazineSize: 30,
    reserveAmmo: 90,
    reloadTime: 2500, // ms
    spread: 0.02,
    spreadRunning: 0.06,
    spreadJumping: 0.10,
    spreadCrouching: 0.012,
    spreadAiming: 0.008,
    spreadIncreasePerShot: 0.003,
    maxSpread: 0.10,
    recoilPerShot: { x: 0.02, y: 0.005 },
    recoilRecovery: 0.92,
    aimZoom: 0.75,
    range: 200,
    penetration: true,
    description: 'Versatile automatic rifle. Good damage and accuracy.',
    accuracy: 7,
    firepower: 8
  },

  pistol: {
    id: 'pistol',
    name: 'Tactical Pistol',
    type: 'secondary',
    price: 500,
    damage: 25,
    headshotMultiplier: 2.5,
    legMultiplier: 0.75,
    fireRate: 200,
    automatic: false,
    magazineSize: 15,
    reserveAmmo: 45,
    reloadTime: 1800,
    spread: 0.015,
    spreadRunning: 0.04,
    spreadJumping: 0.08,
    spreadCrouching: 0.008,
    spreadAiming: 0.005,
    spreadIncreasePerShot: 0.005,
    maxSpread: 0.08,
    recoilPerShot: { x: 0.015, y: 0.003 },
    recoilRecovery: 0.95,
    aimZoom: 0.8,
    range: 100,
    penetration: false,
    description: 'Reliable sidearm. Quick draw and accurate.',
    accuracy: 8,
    firepower: 5
  },

  smg: {
    id: 'smg',
    name: 'Submachine Gun',
    type: 'primary',
    price: 1800,
    damage: 22,
    headshotMultiplier: 2.8,
    legMultiplier: 0.8,
    fireRate: 70,
    automatic: true,
    magazineSize: 35,
    reserveAmmo: 105,
    reloadTime: 2200,
    spread: 0.03,
    spreadRunning: 0.07,
    spreadJumping: 0.12,
    spreadCrouching: 0.018,
    spreadAiming: 0.012,
    spreadIncreasePerShot: 0.004,
    maxSpread: 0.12,
    recoilPerShot: { x: 0.015, y: 0.004 },
    recoilRecovery: 0.90,
    aimZoom: 0.8,
    range: 120,
    penetration: false,
    description: 'High fire rate SMG. Great for close quarters.',
    accuracy: 6,
    firepower: 6
  },

  shotgun: {
    id: 'shotgun',
    name: 'Combat Shotgun',
    type: 'primary',
    price: 2200,
    damage: 15, // per pellet, 8 pellets
    headshotMultiplier: 2.0,
    legMultiplier: 0.8,
    fireRate: 600,
    automatic: false,
    magazineSize: 8,
    reserveAmmo: 32,
    reloadTime: 3000,
    spread: 0.08,
    spreadRunning: 0.12,
    spreadJumping: 0.18,
    spreadCrouching: 0.06,
    spreadAiming: 0.04,
    spreadIncreasePerShot: 0.01,
    maxSpread: 0.18,
    recoilPerShot: { x: 0.06, y: 0.01 },
    recoilRecovery: 0.85,
    aimZoom: 0.8,
    range: 40,
    penetration: false,
    pellets: 8,
    description: 'Devastating at close range. Fires 8 pellets.',
    accuracy: 4,
    firepower: 9
  },

  sniper: {
    id: 'sniper',
    name: 'Sniper Rifle',
    type: 'primary',
    price: 3500,
    damage: 100,
    headshotMultiplier: 4.0,
    legMultiplier: 0.6,
    fireRate: 1200,
    automatic: false,
    magazineSize: 5,
    reserveAmmo: 15,
    reloadTime: 3500,
    spread: 0.001,
    spreadRunning: 0.05,
    spreadJumping: 0.15,
    spreadCrouching: 0.0005,
    spreadAiming: 0.0001,
    spreadIncreasePerShot: 0.001,
    maxSpread: 0.15,
    recoilPerShot: { x: 0.08, y: 0.015 },
    recoilRecovery: 0.80,
    aimZoom: 0.5,
    range: 400,
    penetration: true,
    description: 'High-powered precision rifle. One-shot headshots.',
    accuracy: 10,
    firepower: 10
  }
};

// Starting/default loadout
export const DEFAULT_LOADOUT = {
  primary: null,
  secondary: 'pistol',
  knife: true,
  armor: false,
  grenade: false
};
